AYOQSH/AYOQSH/urls.py
from django.contrib import admin
from django.urls import path, include

# app_name = 'main'
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('fuel.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

AYOQSH/fuel/urls.py
from django.urls import path 
from .import views

app_name = 'main'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('register/', views.register, name='register'),
    path('page/', views.page, name='page'),
    ]

AYOQSH/company/models.py
from django.db import models


from django.db import models
# from django.apps import AppConfig
from django.urls import reverse


class Fuel(models.Model):
    city_name = models.CharField("City_name", max_length=50)
    url = models.SlugField(max_length=100, unique=True)
    company_name = models.CharField("Company_name", max_length=50)
    fuel1 = models.CharField('AI-80', max_length=50, default='')
    feul2 = models.CharField('AI-90', max_length=50, default='')
    feul3 = models.CharField('AI-91', max_length=50, default='')
    feul4 = models.CharField('AI-92', max_length=50, default='')
    feul5 = models.CharField('AI-95', max_length=50, default='')

    
    class Meta:
        verbose_name = "Fuel"
        verbose_name_plural = "Fuel"

    def __str__(self):
        return self.city_name

    def get_absolute_url(self):
        return reverse("filter", kwargs={"slug": self.url})

AYOQSH/fuel/models.py
from django.db import models


from django.urls import reverse


class Fuel(models.Model):
    city_name = models.CharField("City_name", max_length=50)
    url = models.SlugField(max_length=100, unique=True)
    company_name = models.CharField("Company_name", max_length=50)
    fuel1 = models.CharField('AI-80', max_length=50, default='')
    fuel2 = models.CharField('AI-90', max_length=50, default='')
    fuel3 = models.CharField('AI-91', max_length=50, default='')
    fuel4 = models.CharField('AI-92', max_length=50, default='')
    fuel5 = models.CharField('AI-95', max_length=50, default='')

    
    class Meta:
        verbose_name = "Fuel"
        verbose_name_plural = "Fuel"

    def __str__(self):
        return self.city_name

    def get_absolute_url(self):
        return reverse("detail", kwargs={"slug": self.url})

AYOQSH/fuel/views.py
from django.shortcuts import render
from django.views.generic.base import View
from django.views.generic import DetailView
from .models import Fuel
from django.shortcuts import render


# def index(request):
#     return render(request, 'main/index.html',)


def register(request):
    return render(request, 'main/register.html')


def page(request):
    return render(request, 'main/detail.html')



class HomeView(View):
    def get(self, request):
        fuels = Fuel.objects.all()
        return render(request, "main/index.html", {"fuel_list": fuels})

AYOQSH/main/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'main/index.html')


def register(request):
    return render(request, 'main/register.html')




def about(request):
    return render(request, 'main/about.html')

AYOQSH/templates/main/account.html
{% extends 'main/base.html' %}
{% load static %}

{% block tittle %}
Account
{% endblock %}


{% block content %}


{% endblock %}

AYOQSH/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"> 
    <link rel="stylesheet" href="{% static 'css/style.css' %}"> 
    <link rel="stylesheet" href="{% static 'css/bbb.css' %}"> 
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <title>{% block tittle %}{% endblock %}</title>
  
    <style>
      html,
      body {
        position: relative;
        height: 100%;
      }
  
      body {
        background-color: white;
        font-family: Helvetica Neue, Helvetica, Arial, sans-serif;
        font-size: 14px;
        color: #000;
        margin: 0;
        padding: 0;
      }
  
    
      
      .swiper {
        margin-top: 50px;
        margin-bottom: 50px;
        width: 95%;
        height: 50%;
      }
      .swiper-slide {
        border-radius: 10px;
        text-align: center;
        font-size: 18px;
        background: transparent;
        display: flex;
        justify-content: center;
        align-items: center;
      }
  
    
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'main:home' %}">AYOQSH</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'main:home' %}">Home</a>
              </li>
              
              <li class="nav-item">
                <a class="nav-link" href="{% url 'main:register' %}">Register</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Categories
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#contact">Contact</a></li>
                  <li><a class="dropdown-item" href="#about">About Us</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
              
            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>

  

    
    
    {% block content %}
      {% endblock %}

    




     

   

   
        
        <footer class="footer-08" data-aos="zoom-in">
          <div class="container-fluid px-lg-5">
            <div class="row">
              <div class="col-md-9 py-5">
                <div class="row">
                  <div class="col-md-4 mb-md-0 mb-4">
                    <h2 class="footer-heading" id="about">About us</h2>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Numquam, unde?.</p>
                    <ul class="ftco-footer-social p-0">
                      <li class="ftco-animate"><a href="#" data-toggle="tooltip" data-placement="top" title="Twitter"><i class="fa-brands fa-facebook"></i></a></li>
                      <li class="ftco-animate"><a href="#" data-toggle="tooltip" data-placement="top" title="Facebook"><i class="fa-brands fa-twitter"></i></a></li>
                      <li class="ftco-animate"><a href="#" data-toggle="tooltip" data-placement="top" title="Instagram"><i class="fa-brands fa-instagram"></i></a></li>
                    </ul>
                  </div>
                  <div class="col-md-8">
                    <div class="row justify-content-center">
                      <div class="col-md-12 col-lg-9">
                        <div class="row">
                          <div class="col-md-4 mb-md-0 mb-4">
                            <h2 class="footer-heading">Discover</h2>
                            <ul class="list-unstyled">
                              <li><a href="#" class="py-1 d-block">Buy </a></li>
                              <li><a href="#" class="py-1 d-block">Merchant</a></li>
                              <li><a href="#" class="py-1 d-block">Giving back</a></li>
                              <li><a href="#" class="py-1 d-block">Help &amp; Support</a></li>
                            </ul>
                          </div>
                          <div class="col-md-4 mb-md-0 mb-4">
                            <h2 class="footer-heading">About</h2>
                            <ul class="list-unstyled">
                              <li><a href="#" class="py-1 d-block">Staff</a></li>
                              <li><a href="#" class="py-1 d-block">Team</a></li>
                              <li><a href="#" class="py-1 d-block">Careers</a></li>
                              <li><a href="#" class="py-1 d-block">Blog</a></li>
                            </ul>
                          </div>
                          <div class="col-md-4 mb-md-0 mb-4">
                            <h2 class="footer-heading">Resources</h2>
                            <ul class="list-unstyled">
                              <li><a href="#" class="py-1 d-block">Security</a></li>
                              <li><a href="#" class="py-1 d-block">Global</a></li>
                              <li><a href="#" class="py-1 d-block">Charts</a></li>
                              <li><a href="#" class="py-1 d-block">Privacy</a></li>
                            </ul>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="row mt-md-5">
                  <div class="col-md-12">
                Copyright ©<script>document.write(new Date().getFullYear());</script> All rights reserved | </p>
                  </div>
                </div>
              </div>
              <div class="col-md-3 py-md-5 py-4 aside-stretch-right pl-lg-5">
                <h2 class="footer-heading footer-heading-white" id="contact">Contact us</h2>
                <form action="#" class="contact-form">
                  <div class="form-group">
                    <input type="text" class="form-control" placeholder="Your Name">
                  </div>
                  <div class="form-group">
                    <input type="text" class="form-control" placeholder="Your Email">
                  </div>
                  <div class="form-group">
                    <input type="text" class="form-control" placeholder="Phone number">
                  </div>
                  <div class="form-group">
                    <textarea name="" id="" cols="30" rows="3" class="form-control" placeholder="Message"></textarea>
                  </div>
                  <div class="form-group">
                    <button type="submit" class="form-control submit px-3">Send</button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </footer>
        
    
        
      


















        <div class="loader-wrapper">
          <span class="loader"><span class="loader-inner"></span></span>
        </div>

      <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>

      <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
      <!-- <script src="{% static 'js.js' %}"></script> -->
      <script src="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.js"></script>
      <script>
        var swiper = new Swiper(".mySwiper", {
          navigation: {
            nextEl: ".swiper-button-next",
            prevEl: ".swiper-button-prev",
          },
          pagination: {
            el: ".swiper-pagination",
            clickable: true,
          },
          autoplay: {
            delay: 2500,
            disableOnInteraction: false,
          },
        }); 
        AOS.init();
        let loader = document.querySelector('.loader-wrapper')

        window.addEventListener("load", function(){
          loader.style.display = "none"
        })
      </script>
</body>
</html>

AYOQSH/templates/main/datail.html
{% extends 'main/base.html' %}
{% load static %}

{% block tittle %}
Datil
{% endblock %}

{% block block %}

<div class="container">

    <div class="d-lg-flex d-block">

       {% for f in fuel_list %}
       <div class="card m-2" data-aos="fade-right" data-aos-offset="300" data-aos-easing="ease-in-sine">
        <div class="  rounded d-flex ">
            <img class="  h-100  rounded ms-2 mt-2" style="width: 40%;"  src="{% static 'img/ayoqsh.png' %}" alt="">
            <div class="">
                <p class="ms-5 mt-2 fw-bold fs-4   font-monospace ">{{ f.company_name }}</p>
                <p class="ms-4  fw-medium ">Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi, tenetur.</p>
            </div>
        </div>
            <div class="ms-2 mt-5">
                <a href="#" class=" text-bg-light"><p class="  fw-bold"><i class="fa-solid fa-gas-pump"></i> :  AI-80 <i class="fa-sharp fa-solid fa-money-check-dollar ms-5"> : {{ f.fuel1 }} SO'M</i></p></a>
                <a href="#" class=" text-bg-light"><p class="  fw-bold"><i class="fa-solid fa-gas-pump"></i> :  AI-80 <i class="fa-sharp fa-solid fa-money-check-dollar ms-5"> : {{ f.feul2 }} SO'M</i></p></a>
                <a href="#" class=" text-bg-light"><p class="  fw-bold"><i class="fa-solid fa-gas-pump"></i> :  AI-80 <i class="fa-sharp fa-solid fa-money-check-dollar ms-5"> : {{ f.feul3 }} SO'M</i></p></a>
                <a href="#" class=" text-bg-light"><p class="  fw-bold"><i class="fa-solid fa-gas-pump"></i> :  AI-80 <i class="fa-sharp fa-solid fa-money-check-dollar ms-5"> : {{ f.feul4 }} SO'M</i></p></a>
            </div>

                                
            </div>
            
            <br>    
            <br>    
            {% endfor %} 
    </div>
   


    <iframe data-aos="zoom-in" class="w-100 mt-5 " style="height: 400px;" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d48426.049077491465!2d72.19862886542494!3d40.66012841025954!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x38bc8e7780f2771f%3A0x8b87e914ee597fb6!2z0JDRgdCw0LrQsCwg0KPQt9Cx0LXQutC40YHRgtCw0L0!5e0!3m2!1sru!2s!4v1681023101427!5m2!1sru!2s"   allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
</div>

{% endblock %}

AYOQSH/templates/main/detail.html
{% extends 'main/base.html' %}
{% load static %}

{% block tittle %}
Page
{% endblock %}
{% block content %}

        <div class="container mb-5">
            <div class="card m-2 shadow mb-5  bg-light mt-5" >
                <div class="rounded    fuel_card">
                    <img class="   rounded ms-2 mt-2"   src="{% static 'img/ayoqsh.png' %}" alt="">
                    <div class="">
                        <center><p class=" fw-bold fs-4   font-monospace ">AYOQSH</p></center>
                        <p class="ms-4 me-2  fw-medium ">Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi, tenetur.</p>
                    </div>
                 </div>
                    <div class="ms-3 mt-5">
                        <a href="#" class=" text-bg-light"><p class="  fw-bold"><i class="fa-solid fa-gas-pump"></i> :  AI-80 <i class="fa-sharp fa-solid fa-money-check-dollar ms-5"> : 10-000 SO'M</i></p></a>
                        <a href="#" class=" text-bg-light"><p class="  fw-bold"><i class="fa-solid fa-gas-pump"></i> :  AI-80 <i class="fa-sharp fa-solid fa-money-check-dollar ms-5"> : 10-000 SO'M</i></p></a>
                        <a href="#" class=" text-bg-light"><p class="  fw-bold"><i class="fa-solid fa-gas-pump"></i> :  AI-80 <i class="fa-sharp fa-solid fa-money-check-dollar ms-5"> : 10-000 SO'M</i></p></a>
                        <a href="#" class=" text-bg-light"><p class="  fw-bold"><i class="fa-solid fa-gas-pump"></i> :  AI-80 <i class="fa-sharp fa-solid fa-money-check-dollar ms-5"> : 10-000 SO'M</i></p></a>
                    </div>
                    <center>
                        <button class="btn btn-warning w-50  w-lg-25 mt-3 mb-3">Buy Now</button>  
                    </center>                 
        </div> 
        <iframe data-aos="zoom-in" class="w-100 mt-5 " style="height: 400px;" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d48426.049077491465!2d72.19862886542494!3d40.66012841025954!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x38bc8e7780f2771f%3A0x8b87e914ee597fb6!2z0JDRgdCw0LrQsCwg0KPQt9Cx0LXQutC40YHRgtCw0L0!5e0!3m2!1sru!2s!4v1681023101427!5m2!1sru!2s"   allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>

        </div>
{% endblock %}

        

AYOQSH/templates/main/index.html
{% extends 'main/base.html' %}
{% load static %}

{% block tittle %}
AYOQSH
{% endblock %}

<style>

</style>
{% block content %}
            <div class="swiper mySwiper">
                <div class="swiper-wrapper">  
                <div class="swiper-slide"><a href="#"><img class="w-75"    src="{% static 'img/ayoqsh.png' %}" alt=""></a></div>
                <div class="swiper-slide"><a href="#"><img class="w-75"    src="{% static 'img/ayoqsh.png' %}" alt=""></a></div>
                <div class="swiper-slide"><a href="#"><img class="w-75"    src="{% static 'img/ayoqsh.png' %}" alt=""></a></div>
                <div class="swiper-slide"><a href="#"><img class="w-75"    src="{% static 'img/ayoqsh.png' %}" alt=""></a></div>
                <div class="swiper-slide"><a href="#"><img class="w-75"    src="{% static 'img/ayoqsh.png' %}" alt=""></a></div>
                </div>
                <div class="swiper-button-next"></div>
                <div class="swiper-button-prev"></div>
                <div class="swiper-pagination"></div>
            </div>
    <div class="">

        <div class="container align-content-center justify-content-center">
            
        
            
        <center>
            <div class="card-flex">
                <div class="card-hover delete1">
                    <div class="card-hover__content">
                      <h3 class="card-hover__title">
                        <span></span> AYOQSH 
                      </h3>
                      <p class="card-hover__text">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Officia quisquam doloremque nostrum laboriosam, blanditiis libero corporis nulla a aut?</p>
                      <a href="{% url 'main:page' %}" class="card-hover__link">
                        <span>Read More</span>
                        <svg fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
                          <path stroke-linecap="round" stroke-linejoin="round" d="M13.5 4.5L21 12m0 0l-7.5 7.5M21 12H3" />
                        </svg>        
                      </a>
                    </div>
                    <div class="card-hover__extra">
                      <h4>Buy <span>now</span> and get <span>40%</span> discount!</h4>
                    </div>
                    <img src="{% static 'img/fuel.jpg' %}" alt="">
                  </div>
                  

                  <div class="card-hover">
                    <div class="card-hover__content">
                      <h3 class="card-hover__title">
                        <span></span> AYOQSH 
                      </h3>
                      <p class="card-hover__text">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Officia quisquam doloremque nostrum laboriosam, blanditiis libero corporis nulla a aut?</p>
                      <a href="{% url 'main:page' %}" class="card-hover__link">
                        <span>Read More</span>
                        <svg fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
                          <path stroke-linecap="round" stroke-linejoin="round" d="M13.5 4.5L21 12m0 0l-7.5 7.5M21 12H3" />
                        </svg>        
                      </a>
                    </div>
                    <div class="card-hover__extra">
                      <h4>Buy <span>now</span> and get <span>40%</span> discount!</h4>
                    </div>
                    <img src="{% static 'img/fuel.jpg' %}" alt="">
                  </div>

                  <div class="card-hover">
                    <div class="card-hover__content">
                      <h3 class="card-hover__title">
                        <span></span> AYOQSH 
                      </h3>
                      <p class="card-hover__text">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Officia quisquam doloremque nostrum laboriosam, blanditiis libero corporis nulla a aut?</p>
                      <a href="{% url 'main:page' %}" class="card-hover__link">
                        <span>Read More</span>
                        <svg fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
                          <path stroke-linecap="round" stroke-linejoin="round" d="M13.5 4.5L21 12m0 0l-7.5 7.5M21 12H3" />
                        </svg>        
                      </a>
                    </div>
                    <div class="card-hover__extra">
                      <h4>Buy <span>now</span> and get <span>40%</span> discount!</h4>
                    </div>
                    <img src="{% static 'img/fuel.jpg' %}" alt="">
                  </div>
            </div>
        </center>

            <!-- <div class="card m-2" >
                    <div class="rounded  fuel_card">
                        <div class="">
                            <center><p class=" fw-bold fs-4   font-monospace ">AYOQSH</p></center>
                            <p class="ms-4 me-2  fw-medium ">Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi, tenetur.</p>
                        </div>
                     </div>
                        <div class="ms-2 mt-5">
                            <a href="#" class=" text-bg-light"><p class="  fw-bold"><i class="fa-solid fa-gas-pump"></i> :  AI-80 <i class="fa-sharp fa-solid fa-money-check-dollar ms-5"> : {{ f.fuel1 }} SO'M</i></p></a>
                            <a href="#" class=" text-bg-light"><p class="  fw-bold"><i class="fa-solid fa-gas-pump"></i> :  AI-80 <i class="fa-sharp fa-solid fa-money-check-dollar ms-5"> : {{ f.feul2 }} SO'M</i></p></a>
                            <a href="#" class=" text-bg-light"><p class="  fw-bold"><i class="fa-solid fa-gas-pump"></i> :  AI-80 <i class="fa-sharp fa-solid fa-money-check-dollar ms-5"> : {{ f.feul3 }} SO'M</i></p></a>
                            <a href="#" class=" text-bg-light"><p class="  fw-bold"><i class="fa-solid fa-gas-pump"></i> :  AI-80 <i class="fa-sharp fa-solid fa-money-check-dollar ms-5"> : {{ f.feul4 }} SO'M</i></p></a>
                        </div>
                        <center>
                            <button class="btn btn-warning w-50  w-lg-25 mt-3 mb-3"> Read more</button>  
                        </center>                 
            </div>
           -->
            
           
        <iframe data-aos="zoom-in" class="w-100 mt-5 " style="height: 400px;" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d48426.049077491465!2d72.19862886542494!3d40.66012841025954!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x38bc8e7780f2771f%3A0x8b87e914ee597fb6!2z0JDRgdCw0LrQsCwg0KPQt9Cx0LXQutC40YHRgtCw0L0!5e0!3m2!1sru!2s!4v1681023101427!5m2!1sru!2s"   allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                        
        </div>
        
            
            
            
        </div>
       


    </div>
    <br><br>

{% endblock %}

AYOQSH/templates/main/register.html
{% extends 'main/base.html' %}
{% load static %}

{% block tittle %}
Register form
{% endblock %}


{% block content %}

<section class="vh-100" style="background-color: #508bfc;">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-8 col-lg-6 col-xl-5">
          <div class="card shadow-2-strong" style="border-radius: 1rem;">
            <div class="card-body p-5 text-center">
  
              <h3 class="mb-5">Sign in</h3>
  
              <div class="form-outline mb-4">
                <input type="email" id="typeEmailX-2" class="form-control form-control-lg" />
                <label class="form-label" for="typeEmailX-2">Email</label>
              </div>
  
              <div class="form-outline mb-4">
                <input type="password" id="typePasswordX-2" class="form-control form-control-lg" />
                <label class="form-label" for="typePasswordX-2">Password</label>
              </div>
  
              <div class="form-check d-flex justify-content-start mb-4">
                <input class="form-check-input" type="checkbox" value="" id="form1Example3" />
                <label class="form-check-label" for="form1Example3"> Remember password </label>
              </div>
  
              <button class="btn btn-primary btn-lg btn-block" type="submit">Sign up</button>
  
              <hr class="my-4">
  
              <button class="btn btn-lg btn-block btn-primary" style="background-color: blue;"
                type="submit"><i class="fab fa-google me-2"></i> Sign in with google</button>
             
  
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock %}